// This file is generated automatically by the generateIcons.mjs script. Any changes will be overwritten.

export type IconName =
  | 'BadgePercent'
  | 'BankSolid'
  | 'BadgePercent'
  | 'BankSolid'
  | 'Bell'
  | 'BriefCase'
  | 'BriefCase'
  | 'CaretDown'
  | 'ChartBar'
  | 'ClipBoardList'
  | 'CoinSolid'
  | 'FileCoin'
  | 'HandShake'
  | 'Home'
  | 'MobileExchange'
  | 'MoneyBag'
  | 'MoneyLend'
  | 'MultiUsersOutline'
  | 'MultipleUsers'
  | 'PiggyBank'
  | 'ScrollSolid'
  | 'SignOut'
  | 'SliderSetting'
  | 'SwirlingGalaxy'
  | 'UserCancel'
  | 'UserCheck'
  | 'UserSetting'
  | 'Users'
  | 'UsersOutline'
