
// This file is generated automatically by the generateIcons.mjs script. Any changes will be overwritten.

export type IconName = 
| 'BackArrow'
| 'BadgePercent'
| 'BankSolid'
| 'Bell'
| 'BriefCase'
| 'CaretDown'
| 'ChartBar'
| 'ClipBoardList'
| 'CoinSolid'
| 'EyeIcon'
| 'FileCoin'
| 'HandShake'
| 'Home'
| 'MobileExchange'
| 'MoneyBag'
| 'MoneyLend'
| 'MoreVertical'
| 'MultiUsersOutline'
| 'MultipleUsers'
| 'PiggyBank'
| 'ScrollSolid'
| 'SignOut'
| 'SliderSetting'
| 'StarFilled'
| 'StarOutline'
| 'SwirlingGalaxy'
| 'UserCancel'
| 'UserCheck'
| 'UserSetting'
| 'Users'
| 'UsersOutline'
;

